# Generated by Django 3.2 on 2022-09-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
